[package]
name = "ducko"
version = "0.1.0"
edition = "2024"
description = "A simple tool to generate static sites"
license = "MIT"
repository = "https://github.com/welon0919/ducko"
readme = "README.md"
keywords = ["static-site", "ssg", "blog", "site-generator", "cli"]
categories = ["command-line-utilities", "web-programming"]

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
pulldown-cmark = "0.13.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.18"
anyhow = "1.0.102"
log = "0.4.29"
env_logger = "0.11.9"
tera = "1.20.1"
axum = { version = "0.8.8", features = ["ws"] }
tower-http = { version = "0.6.8", features = ["fs"] }
tokio = { version = "1.50.0", features = ["full"] }
webbrowser = "1.1.0"
fs_extra = "1.3.0"
notify = "8.2.0"
rustyline = { version = "17.0.2", features = ["derive"] }
rust-embed = "8.11.0"
chrono = "0.4.44"
